language: bash

services:
  - docker

env:
  global:
    #change the registry name and username/password to yourself's.
    - ALI_REGISTRY=registry.cn-hangzhou.aliyuncs.com
    - ALI_USERNAME=shanying2008@163.com
    - ALI_PASSWORD=3408636xc
    
before_script:
  - docker login $ALI_REGISTRY -u $ALI_USERNAME  -p $ALI_PASSWORD

script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
    	image_name=${image##*/}
    	docker pull $image
        echo $ALI_REGISTRY
        docker tag $image $ALI_REGISTRY/docker-image-wxc/nexus3.acumos.org-10004/$image_name
    	
    	# push到阿里云仓库
    	docker push $ALI_REGISTRY/docker-image-wxc/nexus3.acumos.org-10004/$image_name
    done
